symfony:
  extends:
    file: common.yml
    service: symfony
  links:
    - mysql

nginx:
  extends:
    file: common.yml
    service: nginx
  links:
    - fpm
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  environment:
    VIRTUAL_HOST: teajut.dev
  volumes_from:
    - fpm

fpm:
  extends:
    file: common.yml
    service: fpm
  entrypoint: /start_fpm.sh
  links:
    - mysql
  volumes:
    # - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./php/fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php/start_fpm.sh:/start_fpm.sh
  volumes_from:
    - symfony

mysql:
  extends:
    file: common.yml
    service: mysql
  ports:
    - 3306:3306
