symfony_prod:
  extends:
    file: common.yml
    service: symfony
  container_name: symfony_prod
  links:
    - mysql_prod
  environment:
    SYMFONY_ENV: prod

nginx_prod:
  extends:
    file: common.yml
    service: nginx
  container_name: nginx_prod
  restart: always
  links:
    - fpm_prod
  volumes:
    - ./nginx/nginx_production.conf:/etc/nginx/conf.d/default.conf
  environment:
    VIRTUAL_HOST: www.teajut.ro


fpm_prod:
  extends:
    file: common.yml
    service: fpm
  restart: always
  container_name: fpm_prod
  links:
    - mysql_prod
  entrypoint: /start_fpm.sh
  # command: php-fpm --allow-to-run-as-root
  volumes:
    - ./php/xdebug_prod.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./php/fpm_prod.conf:/usr/local/etc/php-fpm.conf
    - ./php/start_fpm_prod.sh:/start_fpm.sh
    - ./php/cronfile:/cronfile
  volumes_from:
    - symfony_prod

mysql_prod:
  extends:
    file: common.yml
    service: mysql
  restart: always
  container_name: mysql_prod
